volumes:
  n8n_storage:
  sqlserver_storage:
  postgres_storage:
  qdrant_storage:
  jupyter_lab_storage:
  open-webui:
  ollama_storage:

networks:
  homelab:
    driver: bridge

services:
  ai-parser:
    build:
      context: scripts/extract
      dockerfile: Dockerfile
    container_name: ai-parser
    networks:
      - homelab
    ports:
      - "11233:11233"
    restart: always
    volumes:
      - ./temp:/app/temp
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_MODEL=qwen2.5-coder:14b-instruct-q6_K
