pageInfo:
  title: Nguyen HomeLab

sections: # An array of sections
  - name: AI Servers
    icon: fas fa-server
    items:
      - title: n8n
        description: AI Workflow Builder
        icon: fas fa-cogs
        url: http://10.13.13.4:5678/home/workflows
      - title: ollama be
        description: AI Language Models
        icon: fas fa-brain
        url: http://10.13.13.4:11434
      - title: Open Web UI
        description: AI Web Interface
        icon: fas fa-globe
        url: http://10.13.13.4:11435
      - title: langflow
        description: Flow-based Language AI
        icon: fas code-branch
        url: http://10.13.13.4:7860
      - title: anythingllm
        description: AnythingLLM
        icon: fas fa-brain
        url: http://10.13.13.4:3001
  
  - name: Hosting
    icon: fas fa-chart-line
    items:
      - title: Portainer
        description: Docker Management
        icon: fab fa-docker
        url: http://10.13.13.4:8990
      - title: Ngix Proxy Manager
        description: Reverse Proxy Management
        icon: fas fa-network-wired
        url: http://10.13.13.4:81
      - title: Metabase
        description: Data Visualization
        icon: fas fa-chart-bar
        url: http://10.13.13.4:3000
      - title: Supabase
        description: Cloud Provider
        icon: fas fa-chart-bar
        url: http://10.13.13.4:8000

  - name: Knowledge Base
    icon: fas fa-book
    items:
      - title: LogSeg
        description: Log Segmentation
        icon: fas fa-book
        url: http://10.13.13.4:4001
      - title: Ragflow
        description: AI Knowledge Base
        icon: fas fa-book
        url: http://10.13.13.4:9280
      - title: Dify LLM
        description: Dify LLM flow development
        icon: fas fa-brain
        url: http://10.13.13.4/signin

  - name: Storage
    icon: fas fa-hdd
    items:
      - title: Nextcloud
        description: Nextcloud Database
        icon: fas fa-cloud
        url: http://10.13.13.4:8081
      - title: Jellyfin
        description: Jellyfin Database
        icon: fas fa-film
        url: http://10.13.13.4:8096

  - name: Databases
    icon: fas fa-database
    items:
      - title: SQL Server
        description: Microsoft SQL Server
        icon: fas fa-database
        url: http://
      - title: PostgreSQL
        description: PostgreSQL Database
        icon: fas fa-database
        url: http://
      - title: Qdrant
        description: Vector Database
        icon: fas fa-database
        url: http://

  - name: Development
    icon: fas fa-code
    items:
      - title: Code Server
        description: VS Code in the browser
        icon: fas fa-code
        url: http://10.13.13.4:8442?folder=/config/workspace
      - title: Jupyter Lab
        description: Jupyter Notebook in the browser
        icon: fab fa-python
        url: http://10.13.13.4:8883
  - name: Server Management
    icon: fas fa-code
    items:
      - title: C4Y AI Code Server
        description: VS Code in the browser
        icon: fas fa-code
        url: http://10.13.13.4:8441
      
