volumes:
  n8n_storage:
  ollama_storage:
  postgres_storage:
  qdrant_storage:
  sqlserver_storage:
  devserver_storage:
  open-webui:

networks:
  homelab:
    driver: bridge

services:
  dashy:
    image: lissy93/dashy:latest
    container_name: my-dashboard
    networks:
    - homelab
    ports:
      - "8080:8080"
    volumes:
      - ./dashy-config.yml:/app/user-data/conf.yml
    restart: always

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    networks:
    - homelab
    volumes:
      - ollama_storage:/root/.ollama
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  open-web-ui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-web-ui
    networks:
      - homelab
    ports:
      - "11435:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - open-webui:/app/backend/data
    restart: always

  langflow:
    image: langflowai/langflow:latest
    container_name: langflow
    networks:
      - homelab
    ports:
      - "7860:7860"
    restart: always

  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    networks:
      - homelab
    ports:
      - "5678:5678"
    volumes:
      - n8n_storage:/home/node/.n8n
    environment:
      - N8N_SECURE_COOKIES=false
    restart: always
  
  qlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    networks:
    - homelab
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
    volumes:
      - sqlserver_storage:/var/opt/mssql
    restart: always

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    networks:
    - homelab
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Your_password123
      - POSTGRES_DB=postgres
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    networks:
    - homelab
    restart: always
    ports:
      - 6333:6333
    volumes:
      - qdrant_storage:/qdrant/storage

  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SUDO_PASSWORD=123456
    volumes:
      - devserver_storage:/config
    ports:
      - 8441:8443
    restart: always
