version: "3.8"

networks:
  ai-agentic-chat:
    driver: bridge

services:
  bvms-rag-chat:
    ports:
      - 9001:8001
    build:
      context: .
      dockerfile: Dockerfile.bvms
    env_file:
      - .env
    networks:
      - ai-agentic-chat
    restart: unless-stopped

  imos-rag-chat:
    ports:
      - 9002:8001
    build:
      context: .
      dockerfile: Dockerfile.imos
    env_file:
      - .env
    networks:
      - ai-agentic-chat
    restart: unless-stopped
