version: "3.8"

networks:
  ai-agentic-chat:
    driver: bridge

services:
  bvms-rag-chat:
    ports:
      - 9001:8001
    build:
      context: .
      dockerfile: Dockerfile.bvms
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    networks:
      - ai-agentic-chat
    restart: unless-stopped
